services:
    # O seu App de hábitos (Puxando do seu Docker Hub)
    laravel.test:
        image: 'sleumas/habit-tracker:latest'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8080:80' # Acesse via localhost:8080
        environment:
            LARAVEL_SAIL: 1
            APP_KEY: 'base64:u3m3vX8v9M0Lp5nBvR6T6Y7U8I9O0P1A2B3C4D5E6F7=' # Chave padrão para o app ligar
            APP_DEBUG: 'true'
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: 'habit_tracker'
            DB_USERNAME: 'sail'
            DB_PASSWORD: 'password'
        networks:
            - sail
        depends_on:
            - mysql

    # O Banco de Dados
    mysql:
        image: 'mysql:8.4'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: 'habit_tracker'
            MYSQL_USER: 'sail'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql-prod:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-ppassword"]
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql-prod:
        driver: local